---
###############################################
############ for Development Environment ###############
###############################################

########### machine1.#####################

- hosts: dev-machine1
  roles:
     - { role: apache, host-name: machine1.dev}
     - { role: tomcat7,tomcat-name: machine1-tomcat,tomcat-listen-port: 8030 , tomcat-shutdown-port: 8005 }
     - { role: scripts,  component: web }

########### machine2 #####################

- hosts: de-machine2
  roles:
     - { role: scripts,  component: service }
