---
###############################################
############ for De Environment ###############
###############################################

########### Certification.#####################

- hosts: de-certification
  roles:
     - { role: apache, host-name: certification.mettl.de}
     - { role: tomcat7,tomcat-name: certification-tomcat,tomcat-listen-port: 8030 , tomcat-shutdown-port: 8005 }
     - { role: scripts,  component: web }

########### active mq #####################

- hosts: de-activemq
  roles:
     - { role: scripts,  component: service }
