---
- name: install apache2
  apt: name=apache2 update_cache=yes state=latest

- name: enable mod_rewrite
  apache2_module: name=rewrite state=present

- name: enable mod_proxy
  apache2_module: name=proxy state=present

- name: enable mod_http
  apache2_module: name=proxy_http state=present

- name: enable mod_ajp
  apache2_module: name=proxy_ajp state=present
  notify:
    - start apache

